name: Deploy ApiGateway
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        run: echo ${{secrets.HOST}}
